<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttributeOptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attribute_options')->delete();
        
        \DB::table('attribute_options')->insert(array (
            0 => 
            array (
                'id' => 4,
                'attribute_id' => 7,
                'alternames' => '{"cz": "Prodej", "en": "Sale", "ru": "Продажа"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 17:49:37',
                'updated_at' => '2024-08-11 13:42:37',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 5,
                'attribute_id' => 7,
                'alternames' => '{"cz": "Dlouhodobý pronájem", "en": "Long-term rent", "ru": "Долгосрочная аренда"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 17:49:37',
                'updated_at' => '2024-08-11 13:42:37',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 6,
                'attribute_id' => 8,
                'alternames' => '{"cz": "1+KK", "en": "1+KK", "ru": "1+KK"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:31:00',
                'updated_at' => '2024-05-21 18:31:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'attribute_id' => 8,
                'alternames' => '{"cz": "2+KK", "en": "2+KK", "ru": "2+KK"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:31:00',
                'updated_at' => '2024-05-21 18:31:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'attribute_id' => 8,
                'alternames' => '{"cz": "3+KK", "en": "3+KK", "ru": "3+KK"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:31:00',
                'updated_at' => '2024-05-21 18:31:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'attribute_id' => 9,
                'alternames' => '{"cs": "Cihlová", "en": "Brick", "ru": "Кирпичная"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-07-28 10:09:55',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'attribute_id' => 9,
                'alternames' => '{"cs": "Dřevostavba", "en": "Wooden", "ru": "Деревянная"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-07-28 10:09:55',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'attribute_id' => 9,
                'alternames' => '{"cs": "Kamenná", "en": "Stone", "ru": "Каменная"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-07-28 10:09:55',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 12,
                'attribute_id' => 9,
                'alternames' => '{"cs": "Modulární", "en": "Modular", "ru": "Модульная"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-07-28 10:09:55',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'attribute_id' => 9,
                'alternames' => '{"cs": "Panelová", "en": "Panel", "ru": "Панельная"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-07-28 10:09:55',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'attribute_id' => 10,
                'alternames' => '{"cs": "Velmi dobrý", "en": "Very good", "ru": "Очень хорошее"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:45:41',
                'updated_at' => '2024-06-05 16:04:09',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 15,
                'attribute_id' => 10,
                'alternames' => '{"cs": "Dobrý", "en": "Good", "ru": "Хорошее"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:45:41',
                'updated_at' => '2024-06-05 16:04:09',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'attribute_id' => 10,
                'alternames' => '{"cs": "Novostavba", "en": "New building", "ru": "Новостройка"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:45:41',
                'updated_at' => '2024-06-05 16:04:09',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 17,
                'attribute_id' => 13,
                'alternames' => '{"cz": "Ano", "en": "Yes", "ru": "Да"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:50:35',
                'updated_at' => '2024-05-25 11:36:02',
                'deleted_at' => '2024-05-25 11:36:02',
            ),
            14 => 
            array (
                'id' => 18,
                'attribute_id' => 13,
                'alternames' => '{"cz": "Ne", "en": "No", "ru": "Нет"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:50:35',
                'updated_at' => '2024-05-25 11:36:02',
                'deleted_at' => '2024-05-25 11:36:02',
            ),
            15 => 
            array (
                'id' => 19,
                'attribute_id' => 14,
                'alternames' => '{"cz": "Ano", "en": "Yes", "ru": "Да"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:51:39',
                'updated_at' => '2024-05-25 11:41:02',
                'deleted_at' => '2024-05-25 11:41:02',
            ),
            16 => 
            array (
                'id' => 20,
                'attribute_id' => 14,
                'alternames' => '{"cz": "Ne", "en": "No", "ru": "Нет"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:51:40',
                'updated_at' => '2024-05-25 11:41:02',
                'deleted_at' => '2024-05-25 11:41:02',
            ),
            17 => 
            array (
                'id' => 21,
                'attribute_id' => 15,
                'alternames' => '{"cz": "Ano", "en": "Yes", "ru": "Да"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:53:35',
                'updated_at' => '2024-05-25 11:36:14',
                'deleted_at' => '2024-05-25 11:36:14',
            ),
            18 => 
            array (
                'id' => 22,
                'attribute_id' => 15,
                'alternames' => '{"cz": "Ne", "en": "No", "ru": "Нет"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-21 18:53:35',
                'updated_at' => '2024-05-25 11:36:14',
                'deleted_at' => '2024-05-25 11:36:14',
            ),
            19 => 
            array (
                'id' => 23,
                'attribute_id' => 17,
                'alternames' => '{"cz": "1 SIM karta", "en": "1 SIM card", "ru": "1 сим карта"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-23 18:48:58',
                'updated_at' => '2024-05-23 18:48:58',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 24,
                'attribute_id' => 17,
                'alternames' => '{"cz": "2 SIM karty", "en": "2 SIM card", "ru": "2 сим карты"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-23 18:48:58',
                'updated_at' => '2024-05-23 18:48:58',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'attribute_id' => 21,
                'alternames' => '{"cz": "Za měsíc", "en": "Per month", "ru": "За месяц"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-05-24 16:48:19',
                'updated_at' => '2024-05-26 14:42:43',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 29,
                'attribute_id' => 21,
                'alternames' => '{"cz": "Za den", "en": "Per day", "ru": "За день"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-24 16:48:19',
                'updated_at' => '2024-05-26 14:42:43',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 30,
                'attribute_id' => 21,
                'alternames' => '{"cz": "Za hodinu", "en": "Per hour", "ru": "За час"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-24 16:48:19',
                'updated_at' => '2024-05-26 14:42:43',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 31,
                'attribute_id' => 21,
                'alternames' => '{"cz": "Za provedenou práci", "en": "For work performed", "ru": "За выполненную работу"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-24 16:48:19',
                'updated_at' => '2024-05-26 14:42:43',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 32,
                'attribute_id' => 22,
                'alternames' => '{"cz": "1 GB nebo méně", "en": "1 GB and less", "ru": "1 GB и менее"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 33,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "2 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 34,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "3 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 35,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "4 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 36,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "6 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 37,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "8 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 38,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "12 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 39,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "14 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 40,
                'attribute_id' => 22,
                'alternames' => '{"cz": null, "en": "16 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-05-25 14:58:39',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 41,
                'attribute_id' => 23,
                'alternames' => '{"cz": "16 GB nebo méně", "en": "16 GB and less", "ru": "16 GB и менее"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 42,
                'attribute_id' => 23,
                'alternames' => '{"cz": null, "en": "32 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 43,
                'attribute_id' => 23,
                'alternames' => '{"cz": null, "en": "64 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 44,
                'attribute_id' => 23,
                'alternames' => '{"cz": null, "en": "128 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 45,
                'attribute_id' => 23,
                'alternames' => '{"cz": null, "en": "256 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 46,
                'attribute_id' => 23,
                'alternames' => '{"cz": null, "en": "512 GB", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 47,
                'attribute_id' => 23,
                'alternames' => '{"cz": "1 TB nebo více", "en": "1 TB and more", "ru": "1 TB и более"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-05-25 15:08:54',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 48,
                'attribute_id' => 24,
                'alternames' => '{"cz": "4,4 nebo méně", "en": "4,4 and less", "ru": "4,4 и менее"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-05-25 15:15:31',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 49,
                'attribute_id' => 24,
                'alternames' => '{"cz": null, "en": "4,5 - 5,4", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-05-25 15:15:31',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 50,
                'attribute_id' => 24,
                'alternames' => '{"cz": null, "en": "5,5 - 5,9", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-05-25 15:15:31',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 51,
                'attribute_id' => 24,
                'alternames' => '{"cz": null, "en": "6 - 6,4", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-05-25 15:15:31',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 52,
                'attribute_id' => 24,
                'alternames' => '{"cz": "6,5 nebo více", "en": "6,5 and more", "ru": "6,5 и более"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-05-25 15:15:31',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 53,
                'attribute_id' => 25,
                'alternames' => '{"cz": null, "en": "OLED", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-05-25 15:17:15',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 54,
                'attribute_id' => 25,
                'alternames' => '{"cz": null, "en": "QLED", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-05-25 15:17:15',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 55,
                'attribute_id' => 25,
                'alternames' => '{"cz": null, "en": "LED", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-05-25 15:17:15',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 56,
                'attribute_id' => 25,
                'alternames' => '{"cz": null, "en": "NanoCell", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-05-25 15:17:15',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 57,
                'attribute_id' => 25,
                'alternames' => '{"cz": null, "en": "IPS", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-05-25 15:17:15',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 58,
                'attribute_id' => 14,
                'alternames' => '{"cz": "Ano", "en": "Yes", "ru": "Да"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-26 11:59:51',
                'updated_at' => '2024-08-11 13:41:13',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 59,
                'attribute_id' => 14,
                'alternames' => '[]',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-26 11:59:51',
                'updated_at' => '2024-05-26 12:00:21',
                'deleted_at' => '2024-05-26 12:00:21',
            ),
            53 => 
            array (
                'id' => 60,
                'attribute_id' => 14,
                'alternames' => '{"cz": "Ne", "en": "No", "ru": "Нет"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-26 12:00:56',
                'updated_at' => '2024-08-11 13:41:13',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 61,
                'attribute_id' => 14,
                'alternames' => '{"cz": "Nevadí", "en": "No metter", "ru": "Не важно"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-05-26 12:06:52',
                'updated_at' => '2024-08-11 13:41:13',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 62,
                'attribute_id' => 15,
                'alternames' => '{"cz": "Ano", "en": "Yes", "ru": "Да"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-26 13:06:00',
                'updated_at' => '2024-08-09 20:38:15',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 63,
                'attribute_id' => 15,
                'alternames' => '{"cz": "Ne", "en": "No", "ru": "Нет"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-05-26 13:06:00',
                'updated_at' => '2024-08-09 20:38:15',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 64,
                'attribute_id' => 15,
                'alternames' => '{"cz": "Nevadí", "en": "No metter", "ru": "Не важно"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-05-26 13:06:00',
                'updated_at' => '2024-08-09 20:38:15',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 65,
                'attribute_id' => 13,
                'alternames' => '{"cz": "Ano", "en": "Yes", "ru": "Да"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-06-04 10:48:09',
                'updated_at' => '2024-08-10 16:59:51',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 66,
                'attribute_id' => 13,
                'alternames' => '{"cz": "Ne", "en": "No", "ru": "Нет"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-06-04 10:48:09',
                'updated_at' => '2024-08-10 16:59:51',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 67,
                'attribute_id' => 13,
                'alternames' => '{"cz": "Nevadi", "en": "No metter", "ru": "Неважно"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-06-04 10:48:09',
                'updated_at' => '2024-08-10 16:59:51',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 68,
                'attribute_id' => 30,
                'alternames' => '{"cs": "Dům", "en": "House", "ru": "Дом"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:31:43',
                'updated_at' => '2024-07-15 12:57:20',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 69,
                'attribute_id' => 30,
                'alternames' => '{"cs": "Letní dům", "en": "Summer house", "ru": "Дача"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:31:43',
                'updated_at' => '2024-07-15 12:57:20',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 70,
                'attribute_id' => 30,
                'alternames' => '{"cs": "Chata", "en": "Cottage", "ru": "Коттедж"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:31:43',
                'updated_at' => '2024-07-15 12:57:20',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 71,
                'attribute_id' => 30,
                'alternames' => '{"cs": "Městský dům", "en": "Townhouse", "ru": "Таунхаус"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:31:43',
                'updated_at' => '2024-07-15 12:57:20',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 72,
                'attribute_id' => 31,
                'alternames' => '{"cs": "1 pokoj", "en": "1 room", "ru": "1 комната"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-07-17 10:28:47',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 73,
                'attribute_id' => 31,
                'alternames' => '{"cs": "2 pokoje", "en": "2 rooms", "ru": "2 комнаты"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-07-17 10:28:47',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 74,
                'attribute_id' => 31,
                'alternames' => '{"cs": "3 pokoje", "en": "3 rooms", "ru": "3 комнаты"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-07-17 10:28:47',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 75,
                'attribute_id' => 31,
                'alternames' => '{"cs": "4 pokoje", "en": "4 rooms", "ru": "4 комнаты"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-07-17 10:28:47',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 76,
                'attribute_id' => 31,
                'alternames' => '{"cs": "5 pokoje", "en": "5 rooms", "ru": "5 комнаты"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-07-17 10:28:47',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 77,
                'attribute_id' => 31,
                'alternames' => '{"cs": "6 a více", "en": "6 and more", "ru": "6 и более"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-07-17 10:28:47',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 78,
                'attribute_id' => 7,
                'alternames' => '{"cs": "Krátkodoby pronájem", "en": "Short-term rent", "ru": "Краткосрочная аренда"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-16 10:56:40',
                'updated_at' => '2024-08-11 13:42:37',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 79,
                'attribute_id' => 7,
                'alternames' => '{"cs": "Nevadí", "en": "No matter", "ru": "Не важно"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-07-16 12:10:04',
                'updated_at' => '2024-08-11 13:42:37',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 80,
                'attribute_id' => 33,
                'alternames' => '{"cs": "Все", "en": "Все", "ru": "Все"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-07-17 11:32:19',
                'updated_at' => '2024-08-11 13:48:20',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 81,
                'attribute_id' => 33,
                'alternames' => '{"cs": "Pokoj", "en": "Room", "ru": "Комната"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 11:32:19',
                'updated_at' => '2024-08-11 13:48:20',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 82,
                'attribute_id' => 33,
                'alternames' => '{"cs": "Lůžko", "en": "Bed", "ru": "Койко-место"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 11:32:19',
                'updated_at' => '2024-08-11 13:48:20',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 83,
                'attribute_id' => 34,
                'alternames' => '{"cs": "Všechny", "en": "All", "ru": "Все"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-07-17 11:43:59',
                'updated_at' => '2024-08-11 13:45:06',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 84,
                'attribute_id' => 34,
                'alternames' => '{"cs": "Garáž", "en": "Garage", "ru": "Гараж"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 11:43:59',
                'updated_at' => '2024-08-11 13:45:06',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 85,
                'attribute_id' => 34,
                'alternames' => '{"cs": "Parkovací místo", "en": "Parking space", "ru": "Машиноместо"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 11:43:59',
                'updated_at' => '2024-08-11 13:45:06',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 86,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Kancelář", "en": "Office", "ru": "Офис"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 87,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Obchodní prostor", "en": "Trading area", "ru": "Торговая площадь"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 88,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Skladové prostory", "en": "Storage", "ru": "Склад"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 89,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Výroba", "en": "Production", "ru": "Производство"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 90,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Gastronomie", "en": "Restaurant", "ru": "Общепит"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 91,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Hotel", "en": "Hotel", "ru": "Гостиница"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 92,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Autoservis", "en": "Car service", "ru": "Автосервис"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 93,
                'attribute_id' => 35,
                'alternames' => '{"cs": "Celá budova", "en": "The whole building", "ru": "Здание целиком"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-07-17 13:15:14',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 94,
                'attribute_id' => 36,
                'alternames' => '{"cs": "Pro obytnou výstavbu", "en": "For residential development", "ru": "Под жилую застройку"}',
                'is_default' => 1,
                'is_null' => 0,
                'created_at' => '2024-07-17 13:00:03',
                'updated_at' => '2024-07-17 13:12:29',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 95,
                'attribute_id' => 36,
                'alternames' => '{"cs": "V rámci zemědělství", "en": "For agriculture", "ru": "Под сельское хозяйство"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 13:00:03',
                'updated_at' => '2024-07-17 13:12:29',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 96,
                'attribute_id' => 36,
                'alternames' => '{"cs": "Průmyslové", "en": "Industrial", "ru": "Промышленного назначения"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 13:00:03',
                'updated_at' => '2024-07-17 13:12:29',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 97,
                'attribute_id' => 37,
                'alternames' => '{"cs": "Soukromé", "en": "Private", "ru": "Частный"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 13:06:54',
                'updated_at' => '2024-08-11 13:35:41',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 98,
                'attribute_id' => 37,
                'alternames' => '{"cs": "Realitní kancelář", "en": "Agency", "ru": "Агентство"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-17 13:06:54',
                'updated_at' => '2024-08-11 13:35:41',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 99,
                'attribute_id' => 37,
                'alternames' => '{"cs": "Nevadí", "en": "No matter", "ru": "Не важно"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-07-17 13:06:54',
                'updated_at' => '2024-08-11 13:35:41',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 100,
                'attribute_id' => 40,
                'alternames' => '{"cs": "1", "en": "1", "ru": "1"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-26 12:53:24',
                'updated_at' => '2024-07-28 10:37:46',
                'deleted_at' => '2024-07-28 10:37:46',
            ),
            94 => 
            array (
                'id' => 101,
                'attribute_id' => 40,
                'alternames' => '{"cs": "2", "en": "2", "ru": "2"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-07-26 12:53:24',
                'updated_at' => '2024-07-28 10:37:46',
                'deleted_at' => '2024-07-28 10:37:46',
            ),
            95 => 
            array (
                'id' => 102,
                'attribute_id' => 40,
                'alternames' => '{"cs": "3", "en": "3", "ru": "3"}',
                'is_default' => 1,
                'is_null' => 1,
                'created_at' => '2024-07-26 12:53:24',
                'updated_at' => '2024-07-28 10:37:46',
                'deleted_at' => '2024-07-28 10:37:46',
            ),
            96 => 
            array (
                'id' => 103,
                'attribute_id' => 41,
                'alternames' => '{"cs": "Kc", "en": "CZK", "ru": "CZK"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-10 11:38:44',
                'updated_at' => '2024-08-10 11:38:44',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 104,
                'attribute_id' => 41,
                'alternames' => '{"cs": null, "en": "USD", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-10 11:38:44',
                'updated_at' => '2024-08-10 11:38:44',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 105,
                'attribute_id' => 41,
                'alternames' => '{"cs": null, "en": "EUR", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-10 11:38:44',
                'updated_at' => '2024-08-10 11:38:44',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 106,
                'attribute_id' => 42,
                'alternames' => '{"cs": null, "en": "CZK", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-10 18:07:00',
                'updated_at' => '2024-08-10 18:07:00',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 107,
                'attribute_id' => 42,
                'alternames' => '{"cs": null, "en": "EUR", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-10 18:07:00',
                'updated_at' => '2024-08-10 18:07:00',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 108,
                'attribute_id' => 42,
                'alternames' => '{"cs": null, "en": "USD", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-10 18:07:00',
                'updated_at' => '2024-08-10 18:07:00',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 109,
                'attribute_id' => 4,
                'alternames' => '{"cs": null, "en": "CZK", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 09:48:33',
                'updated_at' => '2024-08-14 09:48:33',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 110,
                'attribute_id' => 4,
                'alternames' => '{"cs": null, "en": "USD", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 09:48:33',
                'updated_at' => '2024-08-14 09:48:33',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 111,
                'attribute_id' => 4,
                'alternames' => '{"cs": null, "en": "EUR", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 09:48:33',
                'updated_at' => '2024-08-14 09:48:33',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 112,
                'attribute_id' => 6,
                'alternames' => '{"cs": null, "en": "CZK", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 10:08:37',
                'updated_at' => '2024-08-14 10:08:37',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 113,
                'attribute_id' => 6,
                'alternames' => '{"cs": null, "en": "USD", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 10:08:37',
                'updated_at' => '2024-08-14 10:08:37',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 114,
                'attribute_id' => 6,
                'alternames' => '{"cs": null, "en": "EUR", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 10:08:37',
                'updated_at' => '2024-08-14 10:08:37',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 115,
                'attribute_id' => 38,
                'alternames' => '{"cs": null, "en": "CZK", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 10:11:47',
                'updated_at' => '2024-08-14 10:11:47',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 116,
                'attribute_id' => 38,
                'alternames' => '{"cs": null, "en": "USD", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 10:11:47',
                'updated_at' => '2024-08-14 10:11:47',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 117,
                'attribute_id' => 38,
                'alternames' => '{"cs": null, "en": "EUR", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-14 10:11:47',
                'updated_at' => '2024-08-14 10:11:47',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 118,
                'attribute_id' => 44,
                'alternames' => '{"cs": "BMW", "en": "BMW", "ru": "BMW"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:12:07',
                'updated_at' => '2024-08-17 16:24:10',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 119,
                'attribute_id' => 44,
                'alternames' => '{"cs": "Honda", "en": "Honda", "ru": "Honda"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:12:07',
                'updated_at' => '2024-08-17 16:12:07',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 120,
                'attribute_id' => 44,
                'alternames' => '{"cs": "Mercedes", "en": "Mercedes", "ru": "Mercedes"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:12:07',
                'updated_at' => '2024-08-17 16:12:07',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 121,
                'attribute_id' => 45,
            'alternames' => '{"cs": "BMW 1 (F20)", "en": "BMW 1 (F20)", "ru": "BMW 1 (F20)"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:20:14',
                'updated_at' => '2024-08-17 16:20:14',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 122,
                'attribute_id' => 45,
            'alternames' => '{"cs": "BMW 1 (F52)", "en": "BMW 1 (F52)", "ru": "BMW 1 (F52)"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:20:14',
                'updated_at' => '2024-08-17 16:20:14',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 123,
                'attribute_id' => 45,
                'alternames' => '{"cs": "BMW 2", "en": "BMW 2", "ru": "BMW 2"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:20:14',
                'updated_at' => '2024-08-17 16:20:14',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 124,
                'attribute_id' => 45,
                'alternames' => '{"cs": "BMW 02", "en": "BMW 02", "ru": "BMW 02"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:20:14',
                'updated_at' => '2024-08-17 16:20:14',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 125,
                'attribute_id' => 46,
                'alternames' => '{"cs": "Accord", "en": "Accord", "ru": "Accord"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:43:28',
                'updated_at' => '2024-08-17 16:43:28',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 126,
                'attribute_id' => 46,
                'alternames' => '{"cs": "City", "en": "City", "ru": "City"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:43:28',
                'updated_at' => '2024-08-17 16:43:28',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 127,
                'attribute_id' => 46,
                'alternames' => '{"cs": "Civic", "en": "Civic", "ru": "Civic"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-17 16:43:28',
                'updated_at' => '2024-08-17 16:43:28',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 128,
                'attribute_id' => 48,
                'alternames' => '{"cs": "Sedan", "en": "Sedan", "ru": "Седан"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:01:28',
                'updated_at' => '2024-08-18 11:01:28',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 129,
                'attribute_id' => 48,
                'alternames' => '{"cs": "Coupé", "en": "Coupe", "ru": "Купе"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:01:28',
                'updated_at' => '2024-08-18 11:01:28',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 130,
                'attribute_id' => 48,
                'alternames' => '{"cs": "Hatchback", "en": "Hatchback", "ru": "Хэтчбек"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:01:28',
                'updated_at' => '2024-08-18 11:02:13',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 131,
                'attribute_id' => 49,
                'alternames' => '{"cs": null, "en": "1", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 132,
                'attribute_id' => 49,
                'alternames' => '{"cs": null, "en": "2", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 133,
                'attribute_id' => 49,
                'alternames' => '{"cs": null, "en": "3", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 134,
                'attribute_id' => 49,
                'alternames' => '{"cs": null, "en": "4", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 135,
                'attribute_id' => 49,
                'alternames' => '{"cs": null, "en": "5", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 136,
                'attribute_id' => 49,
                'alternames' => '{"cs": null, "en": "6", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 137,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "1", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 138,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "2", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 139,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "3", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 140,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "4", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 141,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "5", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 142,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "6", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 143,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "7", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 144,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "8", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 145,
                'attribute_id' => 50,
                'alternames' => '{"cs": null, "en": "9", "ru": null}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 146,
                'attribute_id' => 51,
                'alternames' => '{"cs": "Benzín", "en": "Gasoline", "ru": "Бензин"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 147,
                'attribute_id' => 51,
                'alternames' => '{"cs": "Diesel", "en": "Diesel", "ru": "Дизель"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 148,
                'attribute_id' => 51,
                'alternames' => '{"cs": "LPG + benzín", "en": "LPG + gasoline", "ru": "LPG + бензин"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 149,
                'attribute_id' => 51,
                'alternames' => '{"cs": "CNG + benzín", "en": "CNG + gasoline", "ru": "CNG + бензин"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 150,
                'attribute_id' => 51,
                'alternames' => '{"cs": "Elektromobil", "en": "Electric car", "ru": "Электрокар"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 151,
                'attribute_id' => 51,
                'alternames' => '{"cs": "Hybridní", "en": "Hybrid", "ru": "Гибрид"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 152,
                'attribute_id' => 51,
                'alternames' => '{"cs": "Ethanol", "en": "Ethanol", "ru": "Этанол"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 153,
                'attribute_id' => 51,
                'alternames' => '{"cs": "Další", "en": "Other", "ru": "Другое"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 154,
                'attribute_id' => 55,
                'alternames' => '{"cs": "Automatická", "en": "Automatic", "ru": "Автоматическая"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:23:58',
                'updated_at' => '2024-08-19 09:34:21',
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 155,
                'attribute_id' => 55,
                'alternames' => '{"cs": "Manuální", "en": "Manual", "ru": "Ручная"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:23:58',
                'updated_at' => '2024-08-19 09:34:21',
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 156,
                'attribute_id' => 55,
                'alternames' => '{"cs": "Poloautomatické", "en": "Semi-automatic", "ru": "Полуавтоматическая"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:23:58',
                'updated_at' => '2024-08-19 09:34:21',
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 157,
                'attribute_id' => 56,
                'alternames' => '{"cs": "3 stupňová a méně", "en": "3-speed or less", "ru": "3 ступенчатая и меньше"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:32:31',
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 158,
                'attribute_id' => 56,
                'alternames' => '{"cs": "4 stupňová", "en": "4-speed", "ru": "4 ступенчатая"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:32:31',
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 159,
                'attribute_id' => 56,
                'alternames' => '{"cs": "5 stupňová", "en": "5-speed", "ru": "5 ступенчатая"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:32:31',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 160,
                'attribute_id' => 56,
                'alternames' => '{"cs": "6 stupňová", "en": "6-speed", "ru": "6 ступенчатая"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:32:31',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 161,
                'attribute_id' => 56,
                'alternames' => '{"cs": "7 stupňová", "en": "7-speed", "ru": "7 ступенчатая"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:32:31',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 162,
                'attribute_id' => 56,
                'alternames' => '{"cs": "8 stupňová a více", "en": "8-speed and more", "ru": "8 ступенчатая и более"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:32:31',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 163,
                'attribute_id' => 57,
                'alternames' => '{"cs": "4x4", "en": "4x4", "ru": "4x4"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:49:47',
                'updated_at' => '2024-08-19 09:49:47',
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 164,
                'attribute_id' => 57,
                'alternames' => '{"cs": "Pohon předních kol", "en": "Front-wheel drive", "ru": "Передний привод"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:49:47',
                'updated_at' => '2024-08-19 09:49:47',
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 165,
                'attribute_id' => 57,
                'alternames' => '{"cs": "Pohon zadních kol", "en": "Rear-wheel drive", "ru": "Задний привод"}',
                'is_default' => 0,
                'is_null' => 0,
                'created_at' => '2024-08-19 09:49:47',
                'updated_at' => '2024-08-19 09:49:47',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}