<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\TelegramBot',
                'model_id' => 5981959980,
                'uuid' => 'cdc1b6c6-c287-411d-a00b-80c6dbc2b526',
                'collection_name' => 'bots',
                'name' => 'file_235',
                'file_name' => 'file_235.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 35526,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-13 16:03:44',
                'updated_at' => '2024-06-13 16:03:45',
            ),
            1 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 1,
                'uuid' => 'b349a05f-5c88-42f1-8c63-a3e1c868748f',
                'collection_name' => 'categories',
                'name' => 'pngegg-2',
                'file_name' => '01J0GKRMTSA6DS2NNNACHM7WNJ.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 288592,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-16 13:28:40',
                'updated_at' => '2024-06-16 13:28:47',
            ),
            2 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 3,
                'uuid' => '45581fe9-4ba6-4281-83a3-c98b3dcfd6be',
                'collection_name' => 'categories',
                'name' => 'pngegg-3',
                'file_name' => '01J0GTQGGWYW71S48V826Q3BCN.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 49271,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-16 15:30:22',
                'updated_at' => '2024-06-16 15:30:23',
            ),
            3 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 6,
                'uuid' => '8d11b6a8-bc15-47a2-b4b1-c3327cb711ee',
                'collection_name' => 'categories',
                'name' => 'pngegg-5-v1',
                'file_name' => '01J0H1AFXX06S8YFZHZTT8GCRY.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 25418,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-16 17:25:36',
                'updated_at' => '2024-06-16 17:25:39',
            ),
            4 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 2,
                'uuid' => 'ed4303a9-b277-461d-956a-9671404527e5',
                'collection_name' => 'categories',
                'name' => 'pngegg-4-v1',
                'file_name' => '01J0H1CJMFJEX6J5VKARXXKG94.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 28382,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-16 17:26:44',
                'updated_at' => '2024-06-16 17:26:46',
            ),
            5 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\User',
                'model_id' => 1,
                'uuid' => '0868de03-29a2-40e0-808e-2d36c35252ff',
                'collection_name' => 'avatar',
                'name' => 'photo_2024-06-17 12.09.05',
                'file_name' => 'photo_2024-06-17-12.09.05.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 79471,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-17 10:09:09',
                'updated_at' => '2024-06-17 10:09:11',
            ),
            6 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\User',
                'model_id' => 2,
                'uuid' => '7824d06d-673f-439a-a33d-d6ffc21d1c25',
                'collection_name' => 'avatar',
                'name' => 'media-libraryONr2hh',
                'file_name' => 'media-libraryONr2hh',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 1552,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-06-17 11:22:58',
                'updated_at' => '2024-06-17 11:23:00',
            ),
            7 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 8,
                'uuid' => '7bb7950a-b3ae-43b6-b64a-8d1c49867647',
                'collection_name' => 'categories',
                'name' => 'pngegg-21',
                'file_name' => '01J2RCGA2W7XZ1BTSBE1F5F8EK.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 6706,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 10:27:05',
                'updated_at' => '2024-07-14 10:27:07',
            ),
            8 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 10,
                'uuid' => 'f6b0d38f-a3bb-44cc-bc53-4e7bb63300fe',
                'collection_name' => 'categories',
                'name' => 'pngegg-24-v1',
                'file_name' => '01J2RH9BE3Q0CPJRY1RJ7TY8YB.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 27003,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 11:50:40',
                'updated_at' => '2024-07-14 11:50:43',
            ),
            9 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 9,
                'uuid' => 'e0160f94-9984-4738-a6c6-5843d4e13b1d',
                'collection_name' => 'categories',
                'name' => 'pngegg-12-v1',
                'file_name' => '01J2RHBVFC38D4XVJ4N6VXHX4T.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 34384,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 11:52:02',
                'updated_at' => '2024-07-14 11:52:04',
            ),
            10 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 4,
                'uuid' => 'fa4c19e5-f693-4449-9e1c-4862b154da89',
                'collection_name' => 'categories',
                'name' => 'pngegg-11-v1',
                'file_name' => '01J2RHFD851RWX4CSEH2MMFRFK.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 7627,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 11:53:59',
                'updated_at' => '2024-07-14 11:54:00',
            ),
            11 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 11,
                'uuid' => 'ec823e9e-d5da-4f23-b2d2-afda156c481e',
                'collection_name' => 'categories',
                'name' => 'pngegg-25-v1',
                'file_name' => '01J2RJ99PQWSX2T159D2E8T2PN.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 94509,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 12:08:07',
                'updated_at' => '2024-07-14 12:08:08',
            ),
            12 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 12,
                'uuid' => 'b1a2564d-2a57-4a09-8854-fc11b3c3a72d',
                'collection_name' => 'categories',
                'name' => 'pngegg-26-v1',
                'file_name' => '01J2RJKNAPRGDR9403TWYG67E0.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 26578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 12:13:47',
                'updated_at' => '2024-07-14 12:13:48',
            ),
            13 => 
            array (
                'id' => 41,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 13,
                'uuid' => '2dc1e10f-4e3f-463b-9b7c-d02c7ce06ab5',
                'collection_name' => 'categories',
                'name' => 'pngegg-16',
                'file_name' => '01J2RJQVTYZCXK1HW2XVCME1JG.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 56308,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 12:16:04',
                'updated_at' => '2024-07-14 12:16:07',
            ),
            14 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 14,
                'uuid' => '5e50741f-c3e6-43f6-9dfa-312b6e4990a6',
                'collection_name' => 'categories',
                'name' => 'pngegg-27-v1',
                'file_name' => '01J2RKYKB8EG7QN7F8Z0N8GMYE.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 40955,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 12:37:14',
                'updated_at' => '2024-07-14 12:37:16',
            ),
            15 => 
            array (
                'id' => 43,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 15,
                'uuid' => '5be04347-fcb8-43d2-aa59-5bcd737a45a4',
                'collection_name' => 'categories',
                'name' => 'pngegg-17',
                'file_name' => '01J2RN65E9GC4YZKN0QQ7K1E8Y.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 57635,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 12:58:50',
                'updated_at' => '2024-07-14 12:58:53',
            ),
            16 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 16,
                'uuid' => 'f4b8f7aa-79a0-498a-9cbf-414c8c69436c',
                'collection_name' => 'categories',
                'name' => 'pngegg-18-v1',
                'file_name' => '01J2RNDX8CWYVYHVAXZA35CGM5.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 42212,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:03:04',
                'updated_at' => '2024-07-14 13:03:06',
            ),
            17 => 
            array (
                'id' => 45,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 17,
                'uuid' => 'af28b342-61fa-4c43-a469-38427aa5cbb2',
                'collection_name' => 'categories',
                'name' => 'pngegg-28-v1',
                'file_name' => '01J2RNGW94VX4JRSBX83EA1HDB.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 51733,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:04:41',
                'updated_at' => '2024-07-14 13:04:42',
            ),
            18 => 
            array (
                'id' => 47,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 18,
                'uuid' => 'c0ebcbb0-292d-44ad-85b7-104d71f217c4',
                'collection_name' => 'categories',
                'name' => 'pngegg-30-v1',
                'file_name' => '01J2RNSAJ8KGVZYF3C6G70TXTS.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 59157,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:09:18',
                'updated_at' => '2024-07-14 13:09:20',
            ),
            19 => 
            array (
                'id' => 48,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 19,
                'uuid' => '1e0ec650-90db-46ae-86f3-26a4c1b42589',
                'collection_name' => 'categories',
                'name' => 'pngegg-21-v1',
                'file_name' => '01J2RQ2N8CC86T6BK4038JHAEX.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 14007,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:31:52',
                'updated_at' => '2024-07-14 13:31:53',
            ),
            20 => 
            array (
                'id' => 49,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 20,
                'uuid' => 'f0d818b5-904b-4064-b976-167d748df7e0',
                'collection_name' => 'categories',
                'name' => 'pngegg-31-v1',
                'file_name' => '01J2RQ7EY0QHPDX7QABGCRRVG3.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 28573,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:34:30',
                'updated_at' => '2024-07-14 13:34:33',
            ),
            21 => 
            array (
                'id' => 50,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 21,
                'uuid' => 'fa0b3bd7-ee86-42fa-994b-e48885fa95c9',
                'collection_name' => 'categories',
                'name' => 'pngegg-32',
                'file_name' => '01J2RQC369NWHVHCKGZFHPZVTS.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 20827,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:37:02',
                'updated_at' => '2024-07-14 13:37:04',
            ),
            22 => 
            array (
                'id' => 52,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 22,
                'uuid' => 'c1a59b3e-d510-44a0-84f5-d6bf7278eb8f',
                'collection_name' => 'categories',
                'name' => '01J2RQV41TMTJVKFXS8EB9QGDP-thumb-v1',
                'file_name' => '01J2RQWJREMSCN4J29AQA5VAGE.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 32834,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 13:46:02',
                'updated_at' => '2024-07-14 13:46:03',
            ),
            23 => 
            array (
                'id' => 53,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 5,
                'uuid' => 'babe5657-ae2c-4e4b-8c30-3f41b1c8af90',
                'collection_name' => 'categories',
                'name' => 'pngegg-11-v1',
                'file_name' => '01J2RRS0GH061JQ3JRZY6P1086.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 7774,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:01:33',
                'updated_at' => '2024-07-14 14:01:36',
            ),
            24 => 
            array (
                'id' => 54,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 23,
                'uuid' => '1694766b-5381-4b2f-a405-b0cea7459f40',
                'collection_name' => 'categories',
                'name' => 'pngegg-19-v1',
                'file_name' => '01J2RRTFV5YWAVNS244P356A6W.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 47055,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:02:22',
                'updated_at' => '2024-07-14 14:02:24',
            ),
            25 => 
            array (
                'id' => 57,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 25,
                'uuid' => 'cd0b9999-078e-4097-a8a4-2147cce2fb8f',
                'collection_name' => 'categories',
                'name' => '01J2RRXTTATFJPRHC7GASX5Y0G-thumb-v1',
                'file_name' => '01J2RRYQAD7AH7220D92SDH9Z6.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 22381,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:04:41',
                'updated_at' => '2024-07-14 14:04:43',
            ),
            26 => 
            array (
                'id' => 58,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 24,
                'uuid' => 'b0bc1b57-55ba-477b-b0a5-daab8d52b11b',
                'collection_name' => 'categories',
                'name' => '01J2RRWM9JQDZZ1YH7EKG3391X-thumb-v1',
                'file_name' => '01J2RRZWT3023EW2YSRAN5FDS6.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 55450,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:05:19',
                'updated_at' => '2024-07-14 14:05:20',
            ),
            27 => 
            array (
                'id' => 59,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 26,
                'uuid' => '203f2ca1-cd7f-468a-9aa6-45d15b542256',
                'collection_name' => 'categories',
                'name' => 'pngegg-33-v1',
                'file_name' => '01J2RSAZA6PPNG1JDDDFT23A1P.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 23079,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:11:22',
                'updated_at' => '2024-07-14 14:11:24',
            ),
            28 => 
            array (
                'id' => 60,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 7,
                'uuid' => '0cabcaf2-ea9c-460e-ae40-8499e01b745e',
                'collection_name' => 'categories',
                'name' => 'pngegg-6-v1',
                'file_name' => '01J2RSP4TVV4ZZMJ4VHAVEA7NY.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 41118,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:17:28',
                'updated_at' => '2024-07-14 14:17:31',
            ),
            29 => 
            array (
                'id' => 61,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 27,
                'uuid' => 'f7d82f7c-4cdd-477d-a4e1-de00fac095c3',
                'collection_name' => 'categories',
                'name' => '7c76c8726a1d25bbf8e5f40e9437c80d',
                'file_name' => '01J2RT8Y1EAZ4G85FBN9G370MD.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 1106327,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-14 14:27:44',
                'updated_at' => '2024-07-14 14:27:48',
            ),
            30 => 
            array (
                'id' => 62,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 28,
                'uuid' => 'f477e73d-bb82-455d-93a5-0ea00c0df319',
                'collection_name' => 'categories',
                'name' => 'pngegg-5-v1',
                'file_name' => '01J2V4GDSWZC6PS9MG9C25Y8PP.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 25578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-15 12:05:04',
                'updated_at' => '2024-07-15 12:05:06',
            ),
            31 => 
            array (
                'id' => 63,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 29,
                'uuid' => '3b08f5cd-dc65-42d6-8645-18a3406ba325',
                'collection_name' => 'categories',
                'name' => '7c76c8726a1d25bbf8e5f40e9437c80d',
                'file_name' => '01J2V4HZ00YAZ8SR2ZQAD7XTRD.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 1106327,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-15 12:05:54',
                'updated_at' => '2024-07-15 12:05:58',
            ),
            32 => 
            array (
                'id' => 64,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 30,
                'uuid' => '7f81a3b3-fddb-41d0-9b2c-c4ac9479289f',
                'collection_name' => 'categories',
                'name' => 'pngegg-6-v1',
                'file_name' => '01J2V4KD9HPKHZEXSS3Y5MY00A.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 41163,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-15 12:06:42',
                'updated_at' => '2024-07-15 12:06:43',
            ),
            33 => 
            array (
                'id' => 67,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 31,
                'uuid' => '4e3aded6-58eb-4456-a4dc-20d82866d0c4',
                'collection_name' => 'categories',
                'name' => '01J32TR3QT2FN4XEF5TDRGKMWV-thumb-v1',
                'file_name' => '01J32TY4N94HFT2H8FS03AQ4FH.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 35637,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-18 11:51:43',
                'updated_at' => '2024-07-18 11:51:45',
            ),
            34 => 
            array (
                'id' => 69,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 32,
                'uuid' => '10ff331d-b2d8-49c4-81f6-4cf08af1266d',
                'collection_name' => 'categories',
                'name' => '01J32V4J7A178CSE3SR9E9VBBH-thumb-v1',
                'file_name' => '01J32V5HSWQV5JVSMTKJV8QZXG.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 22280,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-18 11:55:46',
                'updated_at' => '2024-07-18 11:55:46',
            ),
            35 => 
            array (
                'id' => 70,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 33,
                'uuid' => '2b069b5e-b485-4ab9-bfd8-d42fdb65ef95',
                'collection_name' => 'categories',
                'name' => 'pngegg-35-v1',
                'file_name' => '01J32V7TVA5XMF5HV5HP3AFJTM.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 63917,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-18 11:57:01',
                'updated_at' => '2024-07-18 11:57:02',
            ),
            36 => 
            array (
                'id' => 71,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 34,
                'uuid' => '3d7f3b40-3ce2-4f64-ac83-f3b67113f3c6',
                'collection_name' => 'categories',
                'name' => 'pngegg-36-v1',
                'file_name' => '01J32VBSCMETMPSR66EZCPDJKD.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 57757,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-18 11:59:10',
                'updated_at' => '2024-07-18 11:59:12',
            ),
            37 => 
            array (
                'id' => 72,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 35,
                'uuid' => '9391ef70-0c14-429a-b194-f3178bbc180f',
                'collection_name' => 'categories',
                'name' => 'pngegg-38-v1',
                'file_name' => '01J32VJZST3WZX47TAF0C80TDB.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 33514,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-18 12:03:06',
                'updated_at' => '2024-07-18 12:03:09',
            ),
            38 => 
            array (
                'id' => 73,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 36,
                'uuid' => 'bd3d2d29-7470-4438-b5bd-ce2b3fd29aeb',
                'collection_name' => 'categories',
                'name' => 'pngegg-39-v1',
                'file_name' => '01J353WCQPF8E9FJHGQSQ7Y09P.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 50002,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:06:32',
                'updated_at' => '2024-07-19 09:06:34',
            ),
            39 => 
            array (
                'id' => 74,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 37,
                'uuid' => '36f0429f-ebd6-445d-aba4-2a012fca1217',
                'collection_name' => 'categories',
                'name' => 'pngegg-40-v1',
                'file_name' => '01J35408G9YJQQZGXVEPM3VMFW.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 35554,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:08:39',
                'updated_at' => '2024-07-19 09:08:40',
            ),
            40 => 
            array (
                'id' => 75,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 38,
                'uuid' => '873c441c-27c2-4845-9f82-c4e2beb9fd32',
                'collection_name' => 'categories',
                'name' => 'pngegg-24',
                'file_name' => '01J3541YHX4TKFAXXKB355YXJG.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 27540,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:09:34',
                'updated_at' => '2024-07-19 09:09:35',
            ),
            41 => 
            array (
                'id' => 76,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 39,
                'uuid' => '2751e80b-770a-4acf-bcbf-d092dd7265e1',
                'collection_name' => 'categories',
                'name' => 'pngegg-41',
                'file_name' => '01J3543DY5QFYD0852TM1FAN5A.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 30377,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:10:22',
                'updated_at' => '2024-07-19 09:10:23',
            ),
            42 => 
            array (
                'id' => 77,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 40,
                'uuid' => 'b818ba90-f3a4-460f-bdaa-58ef470baa84',
                'collection_name' => 'categories',
                'name' => 'pngegg-42-v1',
                'file_name' => '01J3548XRBBVTYHM53BN5JM26D.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 40290,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:13:22',
                'updated_at' => '2024-07-19 09:13:24',
            ),
            43 => 
            array (
                'id' => 78,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 41,
                'uuid' => 'f1634c78-2cec-4b76-87e2-aee4ad5549a1',
                'collection_name' => 'categories',
                'name' => 'pngegg-43-v1',
                'file_name' => '01J355AZEGR2TFXBNVTAV58Z0T.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 6414,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:31:58',
                'updated_at' => '2024-07-19 09:32:00',
            ),
            44 => 
            array (
                'id' => 79,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 42,
                'uuid' => 'e7008fc4-1e61-467a-862d-0322b4818d63',
                'collection_name' => 'categories',
                'name' => 'pngegg-44-v1',
                'file_name' => '01J355EZQ3X4JXTDZXDXYMMEZQ.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 18240,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:34:10',
                'updated_at' => '2024-07-19 09:34:12',
            ),
            45 => 
            array (
                'id' => 80,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 43,
                'uuid' => 'a2351248-88f2-404c-a39e-ff63aa05982f',
                'collection_name' => 'categories',
                'name' => 'pngegg-45-v1',
                'file_name' => '01J355J1H663W4SVP3FB2VTTGJ.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 34948,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:35:50',
                'updated_at' => '2024-07-19 09:35:52',
            ),
            46 => 
            array (
                'id' => 81,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 44,
                'uuid' => '2e57aa00-e42e-4c02-acbe-43bca05eae27',
                'collection_name' => 'categories',
                'name' => 'pngegg-46-v1',
                'file_name' => '01J355QQVJG5A60RHKRRF1T25A.png',
                'mime_type' => 'image/png',
                'disk' => 's3',
                'conversions_disk' => 's3',
                'size' => 21057,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-07-19 09:38:57',
                'updated_at' => '2024-07-19 09:38:59',
            ),
        ));
        
        
    }
}